CIV-11768 Work Allocation for Case Flags
hmcts/civil-wa-task-configuration pull request #496
Opened 2024-01-31 09:57 UTC by jeswanth-hmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-11768

### Change description ###
Work Allocation for Case Flags

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-01-31 13:39 UTC, jeswanth-hmcts commented on src/main/resources/wa-task-permissions-civil-civil.dmn
> -          <text>"Prod"</text>
this change will be added once testing is done  in preview

2024-01-31 13:45 UTC, manish14836 requested changes
Add more specific tests

2024-01-31 14:08 UTC, portizdev commented
Resolve the conflicts and pls add more tests pls. @neeta-hmcts found a way to add specific tests.

2024-01-31 14:58 UTC, jeswanth-hmcts commented
> Resolve the conflicts and pls add more tests pls. @neeta-hmcts found a way to add specific tests.

2024-01-31 14:58 UTC, jeswanth-hmcts commented
added specific  test cases and resolved comments

2024-02-01 09:20 UTC, neeta-hmcts approved these changes

2024-02-06 11:51 UTC, merged